//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessEntity
    {
        public BusinessEntity()
        {
            this.Appointments = new HashSet<Appointment>();
            this.Assets = new HashSet<Asset>();
            this.Customers = new HashSet<Customers>();
            this.Employees = new HashSet<Employee>();
            this.Projects = new HashSet<Project>();
        }
    
        public int EntityId { get; set; }
        public string EntityName { get; set; }
        public decimal EntityContact { get; set; }
        public string EntityContactName { get; set; }
        public string EntityPassword { get; set; }
    
        public virtual ICollection<Appointment> Appointments { get; set; }
        public virtual ICollection<Asset> Assets { get; set; }
        public virtual ICollection<Customers> Customers { get; set; }
        public virtual ICollection<Employee> Employees { get; set; }
        public virtual ICollection<Project> Projects { get; set; }
    }
}
