//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customers
    {
        public Customers()
        {
            this.Appointments = new HashSet<Appointment>();
            this.Projects = new HashSet<Project>();
        }
    
        public int CustomerId { get; set; }
        public string CustomerFirstName { get; set; }
        public string CustomerLastName { get; set; }
        public decimal CustomerPhone { get; set; }
        public string CustomerEmail { get; set; }
        public System.DateTime CustAcqDate { get; set; }
        public int EntityId { get; set; }
    
        public virtual ICollection<Appointment> Appointments { get; set; }
        public virtual BusinessEntity BusinessEntity { get; set; }
        public virtual ICollection<Project> Projects { get; set; }
    }
}
