//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.AppointmentsEmployees = new HashSet<AppointmentsEmployee>();
            this.ProjectsEmployees = new HashSet<ProjectsEmployee>();
        }
    
        public int EmployeeId { get; set; }
        public string EmployeeFirstName { get; set; }
        public string EmployeeLastName { get; set; }
        public decimal EmployeePhone { get; set; }
        public string EmployeeEmail { get; set; }
        public string EmployeeEMcontact { get; set; }
        public decimal EmployeeEMphone { get; set; }
        public System.DateTime EmployeeHireDate { get; set; }
        public Nullable<System.DateTime> EmployeeReleaseDate { get; set; }
        public string Password { get; set; }
        public bool IsPermissions { get; set; }
        public int EntityId { get; set; }
    
        public virtual ICollection<AppointmentsEmployee> AppointmentsEmployees { get; set; }
        public virtual BusinessEntity BusinessEntity { get; set; }
        public virtual ICollection<ProjectsEmployee> ProjectsEmployees { get; set; }
    }
}
