//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public Project()
        {
            this.Assets = new HashSet<Asset>();
            this.ProjectsEmployees = new HashSet<ProjectsEmployee>();
        }
    
        public int ProjectId { get; set; }
        public System.Data.Entity.Spatial.DbGeography ProjectLocation { get; set; }
        public string ProjectDescript { get; set; }
        public decimal ProjectCost { get; set; }
        public decimal ProjectSale { get; set; }
        public int CustomerId { get; set; }
        public System.DateTime ProjectCompletionDate { get; set; }
        public System.DateTime ProjectStartDate { get; set; }
        public int EntityId { get; set; }
    
        public virtual ICollection<Asset> Assets { get; set; }
        public virtual BusinessEntity BusinessEntity { get; set; }
        public virtual Customers Customer { get; set; }
        public virtual ICollection<ProjectsEmployee> ProjectsEmployees { get; set; }
    }
}
